config/routes.rb
Rails.application.routes.draw do

  root :to => "main#index"

  resources :cases

  namespace :admin do
    match '' => 'classic_cases#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :classic_cases

    resources :journalisms
  end

end

app/controllers/admin/main_controller.rb
class Admin::MainController < Admin::AdminController
  layout 'admin_no_sider'

  # 管理员登录
  def login;
  end

  # 验证登录
  def check_login
    login_name = params[:login_name]
    password = params[:password]
    if (login_name == "admin" && password == "admin" )
      #登录成功
      do_admin_login("")
      redirect_to admin_journalisms_path and return
    else
      flash[:notice] = "登录失败，请检查是否填写错误！"
      redirect_to "/admin/login"
    end
  end

  # 退出
  def logout
    session[:admin_id] = nil
    flash[:notice] = "已成功退出"
    redirect_to admin_login_path and return
  end

  def do_admin_login(admin_account)
    session[:admin_id] = 1
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # 最新资讯
    @journalisms = Journalism.order_ct_desc.page(params[:page]).all
    # 经典案例
    @roll = Case.order_ct_desc.page(params[:page]).all
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin/main/login.html.erb
<div class="row-fluid">
  <div class="span12 center login-header">
    <h2>《百合传媒》后台管理系统</h2>
  </div>
  <!--/span-->
</div>
<!--/row-->

<div class="row-fluid">
  <div class="well span5 center login-box">

    <% if flash[:notice] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <%= flash[:notice] %>
        </div>
    <% else %>
        <div class="alert alert-info">
          <button type="button" class="close" data-dismiss="alert">×</button>
          请输入管理员帐号密码
        </div>
    <% end %>

    <%= form_tag check_login_admin_main_index_path, :class => "form-horizontal" do %>
        <fieldset>
          <div class="input-prepend" title="Username" data-rel="tooltip">
            <span class="add-on"><i class="icon-user"></i></span>
            <%= text_field_tag "login_name", nil, :class => "input-large span10", :autofocus => true %>
          </div>
          <div class="clearfix"></div>

          <div class="input-prepend" title="Password" data-rel="tooltip">
            <span class="add-on"><i class="icon-lock"></i></span>
            <%= password_field_tag "password", nil, :class => "input-large span10" %>
          </div>
          <div class="clearfix"></div>

          <p class="center span3">
            <%= submit_tag "登 录", :class => "btn btn-primary" %>
          </p>
        </fieldset>
    <% end %>
  </div>
  <!--/span-->
</div>
<!--/row-->