config/routes.rb
Rails.application.routes.draw do

  root :to => "main#index"

  resources :cases

  namespace :admin do
    match '' => 'classic_cases#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :classic_cases

    resources :journalisms
  end

end

app/models/journalism.rb
class Journalism < ActiveRecord::Base
  validates :title, :presence => {:message => "请填写标题"}, :length => {:maximum => 25, :message => "标题必须小于25个字"}
  validates :descrpiton, :presence => {:message => "请填写内容"}

  attr_accessor :avatar
  has_attached_file :avatar, :styles => {:index => "300x130#", :thumb => "68x48#"}, :default_url => "/images/:style/missing.png",
                    :url => "/case/:id_partition/:style/:filename"
  validates_attachment_size :avatar, :less_than => 2.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/png', 'image/x-png', 'image/jpeg', 'image/pjpeg', 'image/jpg']

  scope :order_ct_desc, lambda { order("created_at DESC") }

  # 删除图片
  def self.deletefile(r_id)
    idstr = format("%09d", r_id.to_s)
    one_path = @filepath+idstr[0, 3]+"/"
    two_path = one_path + idstr[3, 3]+"/"
    three_path = two_path + idstr[6, 3]+"/"
    begin
      `rm -rf #{Rails.root+three_path}`
    rescue
      if system "rm -rf #{Rails.root+three_path}"
        return true
      else
        return false
      end
    end
    return true
  end
end

app/controllers/admin/journalisms_controller.rb
class Admin::JournalismsController < Admin::MainController
  layout 'admin'

  def index
    @journalisms = Journalism.order_ct_desc.page(params[:page]).per(10)
  end

  def new
    @journalism = Journalism.new
  end

  def create
    if request.post?
      if params[:journalism]
        avatar = params[:journalism][:avatar]
        title = params[:journalism][:title]
        descrpiton = params[:journalism][:descrpiton]
        imagename = avatar.original_filename
        avatar.original_filename = Time.now.strftime("%Y%m%d%h%m%s")<<rand(99999).to_s<<imagename[imagename.length-4, 4]
        if !avatar.blank? && !title.blank? && !descrpiton.blank?
          rc = Journalism.create(:avatar => avatar, :title => title, :descrpiton => descrpiton)
          if rc.valid?
          else
            msg = ""
            rc.errors.full_messages.each { |error| msg+= error }
            flash[:error]= msg
            redirect_to :back and return
          end
          redirect_to admin_journalisms_path and return
        else
          flash[:error_msg]="添加失败，请检查添加项是否有空值！"
          redirect_to :back and return
        end
      end
    end
  end

  def edit
    @journalism = Journalism.find(params[:id])
  end

  def update
    @category = Journalism.find(params[:id])
    update_category = @category.update_attributes(
        :title => params[:journalism][:title],
        :descrpiton => params[:journalism][:descrpiton]
    )
    if update_category
      respond_to do |category|
        category.html {
          redirect_to admin_journalisms_path and return
        }
      end
    end
  end

  def show
    @journalism = Journalism.find params[:id]
  end

  #   删除
  def destroy
    @journalism = Case.find params[:id]
    Case.deletefile(@journalism.id)
    @journalism.destroy
    redirect_to admin_journalisms_path and return
  end
end

app/views/admin/journalisms/edit.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_journalisms_path %>">新闻管理</a> <span class="divider">/</span>
    </li>
    <li>
      新闻修改
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 新闻修改</h2>
    </div>
    <div class="box-content">
      <%= form_for @journalism, :url => admin_journalism_path, :method => :put, :html => {:id => "verifytitle"} do |f| %>
          <legend>新闻修改</legend>\
          <%= f.label "新闻标题：" %>
          <%= f.text_field :title %>
          <br/>
          <%= image_tag @journalism.avatar.url(:thumb) %>
          <br/>
          <%= f.label "新闻内容：" %>
          <%= f.text_area :descrpiton, :style => "width:500px;height:150px" %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "journalism[title]": {
                        required: true
                    },
                    "journalism[descrpiton]": {
                        required: true
                    }
                },
                messages: {
                    "journalism[title]": {
                        required: "请填写标题"
                    },
                    "journalism[descrpiton]": {
                        required: "内容不能为空"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/journalisms/index.html.erb
<script>
    <% if flash[:note]%>
    alert('<%=flash[:note]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      新闻列表
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title>
      <h2><i class="icon-list-alt"></i> 新闻列表</h2>
    </div>
    <div class="box-content">
      <div class="form-actions">
        <div style="float: left">
          <%= link_to '添加新闻', new_admin_journalism_path, :class => "btn btn-primary" %>
        </div>
      </div>
      <table class="table table-striped table-bordered bootstrap-datatable datatable">
        <thead>
        <tr>
          <th>ID</th>
          <th>新闻标题</th>
          <th>新闻图文</th>
          <th>创建时间</th>
          <th>详细</th>
          <th>修改</th>
          <th>删除</th>
        </tr>
        </thead>
        <tbody>
        <% @journalisms.each do |q| %>
            <tr>
              <td><%= q.id %></td>
              <td><%= q.title %></td>
              <td><%= image_tag q.avatar.url(:thumb) %></td>
              <td class="center"><%= my_datetime_format q.created_at %></td>
              <td class="center"><%= link_to "详细", admin_journalism_path(q) %></td>
              <td><%= link_to '修改', edit_admin_journalism_path(q) %></td>
              <td><%= link_to '删除', admin_journalism_path(q), :method => :delete, :confirm => "您确定要删除吗?" %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination pagination-centered">
        <ul>
          <%= paginate @journalisms %>
        </ul>
      </div>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->

app/views/admin/journalisms/new.html.erb
<script>
    <% if flash[:error_msg]%>
    alert('<%=flash[:error_msg]%>');
    <% end%>
</script>
<div>
  <ul class="breadcrumb">
    <li>
      <a href="#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_journalisms_path %>">新闻管理</a> <span class="divider">/</span>
    </li>
    <li>
      添加新闻
    </li>
  </ul>
</div>
<div class="row-fluid sortable ui-sortable">
  <div class="box span12">
    <div class="box-header well" data-original-title="">
      <h2><i class="icon-edit"></i> 添加新闻</h2>
    </div>
    <div class="box-content">
      <%= form_for(:journalism, :url => admin_journalisms_path, :method => :post, :html => {:id => "verifytitle"}) do |f| %>
          <legend>添加新闻</legend>
          <%= f.label "新闻标题：" %>
          <%= f.text_field :title %>
          <%= f.label "选择图片：" %>
          <%= f.file_field :avatar %>
          <%= f.label "新闻内容：" %>
          <%= f.text_area :descrpiton, :style => "width:500px;height:150px" %>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">完成提交</button>
          </div>
      <% end %>
    </div>
  </div>
  <!--/span-->
</div>
<script src="/admin/js/jquery.validate.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("#verifytitle").validate({
                rules: {
                    "journalism[title]": {
                        required: true
                    },
                    "journalism[avatar]": {
                        required: true,
                        accept: "jpg|png"
                    },
                    "journalism[descrpiton]": {
                        required: true
                    }
                },
                messages: {
                    "journalism[title]": {
                        required: "请填写标题"
                    },
                    "journalism[avatar]": {
                        required: "请上传图片",
                        accept: "图片类型必须是png或jpg"
                    },
                    "journalism[descrpiton]": {
                        required: "内容不能为空"
                    }
                },
                errorClass: "error",
                highlight: function (element, errorClass) {
                    $(element).parent().parent().addClass(errorClass);
                },
                unhighlight: function (element, errorClass) {
                    $(element).parent().parent().removeClass(errorClass);
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                },
                errorElement: "span"
            });
        });
    });
    $(document).ready(function () {
        $('form[data-remote]').bind('ajax:before', function () {
            for (instance in CKEDITOR.instances) {
                CKEDITOR.instances[instance].updateElement();
            }
        });
    });
</script>

app/views/admin/journalisms/show.html.erb
<div>
  <ul class="breadcrumb">
    <li>
      <a href=#">Home</a> <span class="divider">/</span>
    </li>
    <li>
      <a href="<%= admin_journalisms_path %>">新闻管理</a> <span class="divider">/</span>
    </li>
    <li>
      新闻详细
    </li>
  </ul>
</div>
<div class="row-fluid sortable">
  <div class="box span12">
    <div class="box-content">
      <p>
        新闻分类：<%= @journalism.question_category_name %>
      </p><br/>
      <%= image_tag @roll.avatar.url(:zhengchang) %>
      <br/>
      <p>
        新闻内容：<%= @journalism.descrpiton.html_safe %>
      </p>

      <br/><br/>
    </div>
  </div>
  <!--/span-->
</div><!--/row-->