config/routes.rb
Rails.application.routes.draw do

  root :to => "main#index"

  resources :cases

  namespace :admin do
    match '' => 'classic_cases#index', :via => :get
    match '/login' => 'main#login', :via => :get
    match '/logout' => 'main#logout', :via => :get
    resources :main do
      collection do
        post 'check_login'
      end
    end
    resources :classic_cases

    resources :journalisms
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>《百合传媒》后台管理系统</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content="Charisma, a fully featured, responsive, HTML5, Bootstrap admin template."/>
  <meta name="author" content="Muhammad Usman"/>

  <!-- The styles -->
  <link href="/admin/css/bootstrap-cerulean.css" rel="stylesheet"/>
  <style type="text/css">
      body {
          padding-bottom: 40px;
      }

      .sidebar-nav {
          padding: 9px 0;
      }
  </style>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="/admin/css/bootstrap-responsive.css" rel="stylesheet"/>
  <link href="/admin/css/charisma-app.css" rel="stylesheet"/>
  <link href="/admin/css/jquery-ui-1.8.21.custom.css" rel="stylesheet"/>
  <link href='/admin/css/fullcalendar.css' rel='stylesheet'/>
  <link href='/admin/css/fullcalendar.print.css' rel='stylesheet' media='print'/>
  <link href='/admin/css/chosen.css' rel='stylesheet'/>
  <link href='/admin/css/uniform.default.css' rel='stylesheet'/>
  <link href='/admin/css/colorbox.css' rel='stylesheet'/>
  <link href='/admin/css/jquery.cleditor.css' rel='stylesheet'/>
  <link href='/admin/css/jquery.noty.css' rel='stylesheet'/>
  <link href='/admin/css/noty_theme_default.css' rel='stylesheet'/>
  <link href='/admin/css/elfinder.min.css' rel='stylesheet'/>
  <link href='/admin/css/elfinder.theme.css' rel='stylesheet'/>
  <link href='/admin/css/jquery.iphone.toggle.css' rel='stylesheet'/>
  <link href='/admin/css/opa-icons.css' rel='stylesheet'/>
  <link href='/admin/css/uploadify.css' rel='stylesheet'/>
  <link href='/admin/css/b-search.css' rel='stylesheet'/>
  <link href="/admin/css/b-search.css" rel="stylesheet"/>
  <link href="/admin/css/datepicker.css" rel="stylesheet"/>
  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!-- 兼容 -->
  <meta name="renderer" content="webkit">

  <script src='/admin/js/jquery.validate.js'></script>

</head>

<body>
<!-- topbar starts -->
<div class="navbar">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="<%= admin_journalisms_path %>"> <img alt="Charisma Logo" src="/admin/img/favicon.png"/>
        <span>百合传媒</span></a>

      <!-- user dropdown starts -->
      <div class="btn-group pull-right">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="<%= admin_logout_path %>">
          <i class="icon-user"></i><span class="hidden-phone"> 退出</span>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "注销", admin_logout_path, :class => "link" %></li>
        </ul>
      </div>
      <!-- user dropdown ends -->

      <div class="top-nav nav-collapse">
        <ul class="nav">
          <li><a href="#">Visit Site</a></li>
          <li>
            <form class="navbar-search pull-left">
              <input placeholder="Search" class="search-query span2" name="query" type="text"/>
            </form>
          </li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>
<!-- topbar ends -->
<div class="container-fluid">
  <div class="row-fluid">

    <!-- left menu starts -->
    <div class="span2 main-menu-span">
      <div class="well nav-collapse sidebar-nav">
        <ul class="nav nav-tabs nav-stacked main-menu">
          <li class="nav-header hidden-tablet">导航栏</li>
          <li><%= link_to "<i class=\"icon-home\"></i>首页管理".html_safe %></li>
          <li><%= link_to "<i class=\"icon-home\"></i>经典案例".html_safe, admin_classic_cases_path %></li>
          <li><%= link_to "<i class=\"icon-home\"></i>新闻公告".html_safe, admin_journalisms_path %></li>
        </ul>
        <!--yi bu shua xin ye mian-->
        <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><input id="is-ajax" type="checkbox"/> Ajax on
          menu</label>
      </div>
      <!--/.well -->
    </div>
    <!--/span-->
    <!-- left menu ends -->

    <div id="content" class="span10">
      <!-- content starts -->
      <%= yield %>
      <!-- content ends -->
    </div>
    <!--/#content.span10-->
  </div>
  <!--/fluid-row-->
  <hr/>
</div>
<!--/.fluid-container-->

<!-- external javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!-- date select -->
<script src="/admin/js/tcal.js"></script>

</body>
</html>

app/views/layouts/admin_no_sider.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!--
      Charisma v1.0.0

      Copyright 2012 Muhammad Usman
      Licensed under the Apache License v2.0
      http://www.apache.org/licenses/LICENSE-2.0

      http://usman.it
      http://twitter.com/halalit_usman
  -->
  <meta charset="utf-8"/>
  <title>《百合传媒》后台管理系统</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content="Charisma, a fully featured, responsive, HTML5, Bootstrap admin template."/>
  <meta name="author" content="Muhammad Usman"/>

  <!-- The styles -->
  <link id="bs-css" href="css/bootstrap-cerulean.css" rel="stylesheet"/>
  <style type="text/css">
      body {
          padding-bottom: 40px;
      }

      .sidebar-nav {
          padding: 9px 0;
      }
  </style>
  <link href="css/bootstrap-responsive.css" rel="stylesheet"/>
  <link href="css/charisma-app.css" rel="stylesheet"/>
  <link href="css/jquery-ui-1.8.21.custom.css" rel="stylesheet"/>
  <link href='css/fullcalendar.css' rel='stylesheet'/>
  <link href='css/fullcalendar.print.css' rel='stylesheet' media='print'/>
  <link href='css/chosen.css' rel='stylesheet'/>
  <link href='css/uniform.default.css' rel='stylesheet'/>
  <link href='css/colorbox.css' rel='stylesheet'/>
  <link href='css/jquery.cleditor.css' rel='stylesheet'/>
  <link href='css/jquery.noty.css' rel='stylesheet'/>
  <link href='css/noty_theme_default.css' rel='stylesheet'/>
  <link href='css/elfinder.min.css' rel='stylesheet'/>
  <link href='css/elfinder.theme.css' rel='stylesheet'/>
  <link href='css/jquery.iphone.toggle.css' rel='stylesheet'/>
  <link href='css/opa-icons.css' rel='stylesheet'/>
  <link href='css/uploadify.css' rel='stylesheet'/>

</head>
<body>
<div class="container-fluid">
  <%= yield %>
</div>
<!--/.fluid-container-->

<!-- external javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!-- jQuery -->
<script src="js/jquery-1.7.2.min.js"></script>
<!-- jQuery UI -->
<script src="js/jquery-ui-1.8.21.custom.min.js"></script>
<!-- transition / effect library -->
<script src="js/bootstrap-transition.js"></script>
<!-- alert enhancer library -->
<script src="js/bootstrap-alert.js"></script>
<!-- modal / dialog library -->
<script src="js/bootstrap-modal.js"></script>
<!-- custom dropdown library -->
<script src="js/bootstrap-dropdown.js"></script>
<!-- scrolspy library -->
<script src="js/bootstrap-scrollspy.js"></script>
<!-- library for creating tabs -->
<script src="js/bootstrap-tab.js"></script>
<!-- library for advanced tooltip -->
<script src="js/bootstrap-tooltip.js"></script>
<!-- popover effect library -->
<script src="js/bootstrap-popover.js"></script>
<!-- button enhancer library -->
<script src="js/bootstrap-button.js"></script>
<!-- accordion library (optional, not used in demo) -->
<script src="js/bootstrap-collapse.js"></script>
<!-- carousel slideshow library (optional, not used in demo) -->
<script src="js/bootstrap-carousel.js"></script>
<!-- autocomplete library -->
<script src="js/bootstrap-typeahead.js"></script>
<!-- tour library -->
<script src="js/bootstrap-tour.js"></script>
<!-- library for cookie management -->
<script src="js/jquery.cookie.js"></script>
<!-- calander plugin -->
<script src='js/fullcalendar.min.js'></script>
<!-- data table plugin -->
<script src='js/jquery.dataTables.min.js'></script>

<!-- chart libraries start -->
<script src="js/excanvas.js"></script>
<script src="js/jquery.flot.min.js"></script>
<script src="js/jquery.flot.pie.min.js"></script>
<script src="js/jquery.flot.stack.js"></script>
<script src="js/jquery.flot.resize.min.js"></script>
<!-- chart libraries end -->

<!-- select or dropdown enhancer -->
<script src="js/jquery.chosen.min.js"></script>
<!-- checkbox, radio, and file input styler -->
<script src="js/jquery.uniform.min.js"></script>
<!-- plugin for gallery image view -->
<script src="js/jquery.colorbox.min.js"></script>
<!-- rich text editor library -->
<script src="js/jquery.cleditor.min.js"></script>
<!-- notification plugin -->
<script src="js/jquery.noty.js"></script>
<!-- file manager library -->
<script src="js/jquery.elfinder.min.js"></script>
<!-- star rating plugin -->
<script src="js/jquery.raty.min.js"></script>
<!-- for iOS style toggle switch -->
<script src="js/jquery.iphone.toggle.js"></script>
<!-- autogrowing textarea plugin -->
<script src="js/jquery.autogrow-textarea.js"></script>
<!-- multiple file upload plugin -->
<script src="js/jquery.uploadify-3.1.min.js"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="js/jquery.history.js"></script>
<!-- application script for Charisma demo -->
<script src="js/charisma.js"></script>

<script src='js/jquery.validate.js'></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- saved from url=(0017)http://z3web.net/ -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>吉林省百合文化传媒有限公司-是以道闸挡车杆,龙嘉机场LED,FM94.3,微信开发,网站开发,活动宣传策划为主营的传媒公司。www.jlsgg.com-吉林省百合文化传媒有限公司</title>
  <meta name="author" content="吉林省百合文化传媒有限公司www.jlsgg.com">
  <meta name="keywords" content="长春广告|吉林广告|长春传媒|吉林传媒|道闸|挡车杆|有效广告|宣传媒体|宣传方式|龙嘉机场|LED|活动宣传|活动策划|企业策划长春广告|吉林广告|长春传媒|吉林传媒|道闸|挡车杆|制作|发布|印刷|门户|有效广告|宣传媒体|宣传方式|龙嘉机场|LED|网站开发|域名注册|微信模版开发|微信功能开发|微信|活动宣传|活动策划|企业策划|广告|传媒|策划|宣传|推广www.jlsgg.com">
  <meta name="description" content="吉林省百合文化传媒有限制是以道闸挡车干,龙嘉机场LED,FM94.3,微信开发,网站开发,活动宣传策划为主营的传媒公司。www.jlsgg.com">
  <link href="../stylesheets/style.css" rel="stylesheet" type="text/css">

  <script type="text/javascript" src="../javascripts/jquery.min.js"></script>

  <script type="text/javascript" src="../javascripts/jquery.plugin.js"></script>

  <script type="text/javascript" src="../javascripts/script.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>